### ISSUE TITLE
Could you implement the sam feature for Zset?

### ISSUE THREAD

**Issue by immmus** [Rush/redis_expiremember_module#1]
Hi! Thank you for the module
Could you implement the sam feature for Zset?

**Comment by Rush** [comment]
Shouldn't be too hard. What's your use case?

**Comment by immmus** [comment]
In our case we are using Zset and the transition to Set will be somewhat painful but we really miss the feature and using some workarounds for it. I tested your approach and it works as we need

**Comment by Rush** [comment]
I implemented ZSET. Please let me know your feedback.

You can either use a docker image `rushpl/redis-expiremember` or build this yourself.

**Comment by immmus** [comment]
> I implemented ZSET. Please let me know your feedback.
> 
> You can either use a docker image `rushpl/redis-expiremember` or build this yourself.

I built it myself)

Thank you so much it is working! Nice, I'm very grateful to you for so fast work)

**Comment by Rush** [comment]
I'm glad it's useful. If you have any other ideas or feedback, feel free to open a new ticket.

**Comment by immmus** [comment]
Agreed!
